### ISSUE TITLE
AttributeError: 'Mole' object has no attribute 'precision'

### ISSUE THREAD

**Issue by noyerx** [pyscf/mpi4pyscf#12]
I have the latest PySCF 1.6 and mpi4pyscf, and run the following test:
`OMP_NUM_THREADS=2 mpirun -np 2 python 01-parallel_hf.py 
`
I get the following error:

> Traceback (most recent call last):
>   File "/export/zgid/yanbing/softwareRepo/mpi4pyscf/__init__.py", line 32, in <module>
>     mpi.pool.wait()
>   File "/export/zgid/yanbing/softwareRepo/mpi4pyscf/tools/mpi_pool.py", line 111, in wait
>     ans = self.function(*task)  # task = worker_args
>   File "/export/zgid/yanbing/softwareRepo/mpi4pyscf/tools/mpi.py", line 486, in _init_on_workers
>     obj = cls(*args, **kwargs)
>   File "/export/zgid/yanbing/softwareRepo/pyscf/pyscf/pbc/df/mdf.py", line 331, in __init__
>     self.mesh = _mesh_for_valence(cell)
>   File "/export/zgid/yanbing/softwareRepo/pyscf/pyscf/pbc/df/mdf.py", line 302, in _mesh_for_valence
>     precision = cell.precision * 10
> AttributeError: 'Mole' object has no attribute 'precision'
> application called MPI_Abort(MPI_COMM_WORLD, 0) - process 1

**Comment by sunqm** [comment]
Fixed in commit 88861a8
